Repository brave/ads-ui, pull requests merged in 2024-08, with the labels that each got.

#1288 fix(pages): redirect to dashboard if user is authenticated
  src/auth/components/UserRedirect.tsx
  src/auth/views/components/AuthContainer.tsx
Labels: user-experience

#1287 fix(creatives): make sure selected creatives are correct for the ad set
  src/components/Creatives/CreateCreativeButton.tsx
  src/components/Creatives/CreativeForm.tsx
  src/components/Creatives/CreativeSelect.tsx
  src/locales/en.po
  src/locales/es.po
  src/locales/pt.po
  src/locales/test.po
  src/user/ads/AdsExistingAd.tsx
  src/user/ads/InlineContentAd.tsx
  src/user/ads/NotificationAd.tsx
  src/user/views/adsManager/views/advanced/components/adSet/fields/AdSetAds.tsx
Labels: Bug, user-experience

#1291 fix: switch update profile call to "update self"
  src/graphql-client/gql.ts
  src/graphql-client/graphql.ts
  src/graphql/ads-serve.graphql.schema.json
  src/graphql/user.graphql
  src/user/settings/UserForm.tsx
Labels: puLL-Merge

#1284 feat(graphql): transition to specific campaign update mutation
  src/components/Conversion/ConversionDisplay.tsx
  src/components/Location/LocationPicker.tsx
  src/components/Segment/SegmentPicker.tsx
  src/graphql-client/gql.ts
  src/graphql-client/graphql.ts
  src/graphql/ads-serve.graphql.schema.json
  src/user/ads/NewAd.tsx
  src/user/library/index.test.ts
  src/user/library/index.ts
  src/user/views/adsManager/types/index.ts
  src/user/views/adsManager/views/advanced/components/adSet/AdSetFields.tsx
  src/user/views/adsManager/views/advanced/components/adSet/fields/ConversionField.tsx
  src/user/views/adsManager/views/advanced/components/campaign/CampaignSettings.tsx
  src/user/views/adsManager/views/advanced/components/form/EditCampaign.tsx
  src/user/views/adsManager/views/advanced/components/review/Review.tsx
  src/user/views/adsManager/views/advanced/components/review/components/AdSetReview.tsx
  src/util/segment.ts
  src/validation/CampaignSchema.tsx
Labels: puLL-Merge, depends-on-server-release

#1294 Production Release 2024-08-05
  src/components/Conversion/ConversionDisplay.tsx
  src/components/Location/LocationPicker.tsx
  src/components/Segment/SegmentPicker.tsx
  src/graphql-client/gql.ts
  src/graphql-client/graphql.ts
  src/graphql/ads-serve.graphql.schema.json
  src/graphql/user.graphql
  src/locales/en.po
  src/locales/es.po
  src/locales/pt.po
  src/locales/test.po
  src/user/ads/NewAd.tsx
  src/user/library/index.test.ts
  src/user/library/index.ts
  src/user/settings/UserForm.tsx
  src/user/views/adsManager/types/index.ts
  src/user/views/adsManager/views/advanced/components/adSet/AdSetFields.tsx
  src/user/views/adsManager/views/advanced/components/adSet/fields/ConversionField.tsx
  src/user/views/adsManager/views/advanced/components/campaign/CampaignSettings.tsx
  src/user/views/adsManager/views/advanced/components/form/EditCampaign.tsx
  src/user/views/adsManager/views/advanced/components/review/Review.tsx
  src/user/views/adsManager/views/advanced/components/review/components/AdSetReview.tsx
  src/user/views/user/CampaignView.tsx
  src/user/views/user/ConversionAlert.tsx
  src/util/segment.ts
  src/validation/CampaignSchema.tsx
Labels: puLL-Merge

#1302 feat(login): obtain user consent when verifying magic link
  src/auth/hooks/queries/useAuthorize.ts
  src/auth/lib/index.ts
  src/auth/views/AuthVerify.tsx
  src/auth/views/MagicLink.tsx
  src/auth/views/components/AuthContainer.tsx
Labels: depends-on-server-release

#1303 Production Release 2024-08-06
  src/auth/hooks/queries/useAuthorize.ts
  src/auth/lib/index.ts
  src/auth/registration/Register.tsx
  src/auth/views/AuthVerify.tsx
  src/auth/views/MagicLink.tsx
  src/auth/views/components/AuthContainer.tsx
  src/locales/en.po
  src/locales/es.po
  src/locales/pt.po
  src/locales/test.po
Labels: puLL-Merge

#1309 build: dedupe dependencies
  pnpm-lock.yaml
  renovate.json
Labels: puLL-Merge

#1310 chore(request): PUT should have body, not qs params
  src/checkout/hooks/useValidatePaymentSession.ts
  src/checkout/lib/index.ts
Labels: depends-on-server-release

#1311 Production Release 2024-08-08
  package.json
  pnpm-lock.yaml
  renovate.json
  src/checkout/hooks/useValidatePaymentSession.ts
  src/checkout/lib/index.ts
  src/components/Assets/hooks/useGetImagePreviewUrl.ts
  src/components/Creatives/hooks/useSubmitCreative.tsx
Labels: puLL-Merge

#1313 chore(graphql): update mutation naming convention
  src/auth/components/AdvertiserDetailsForm.tsx
  src/graphql-client/gql.ts
  src/graphql-client/graphql.ts
  src/graphql/ads-serve.graphql.schema.json
Labels: puLL-Merge

#1318 Production Release 2024-08-14
  .github/workflows/codeql-analysis.yml
  package.json
  pnpm-lock.yaml
  src/auth/components/AdvertiserDetailsForm.tsx
  src/graphql-client/gql.ts
  src/graphql-client/graphql.ts
  src/graphql/ads-serve.graphql.schema.json
Labels: puLL-Merge

#1327 fix(payment): allow switching between payment methods
  src/checkout/hooks/useCreatePaymentSession.ts
  src/checkout/lib/index.ts
  src/user/views/adsManager/views/advanced/components/form/EditCampaign.tsx
Labels: depends-on-server-release
